Allow backend to compile with CMake on OS X
1. Added 'include "Python.h"' to top of several sources.
   This fixes errors of form

     error: macro "XYZ" passed 2 arguments, but takes just 1

2. Added some missing dependencies for "trace" target
   to CMakeLists.txt