Remove trailing slashes from package_dir paths.
This causes issues with setuptools <= 19.3, which uses a buggy method to
get the relative paths of files [1]. The symptom is that when adding a
.vnt file in one of these directories, setup.py accidentally cuts off
the first character of the filename, then complains that it doesn't
exist. For example:

$ SKIP_PUMA_BACKEND=1 python setup.py build
running build
running build_py
error: can't copy 'backend/mite/relude.vnt': doesn't exist or not a regular file

[1]: https://github.com/pypa/setuptools/issues/341